# Generated by Django 6.0 on 2025-12-31 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='antivirus_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='انقضای آنتی\u200cویروس'),
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('warranty', 'تمدید گارانتی'), ('antivirus', 'تمدید آنتی\u200cویروس')], max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('duration_months', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات خدمات')),
                ('user_count', models.IntegerField(default=1, verbose_name='تعداد کاربر (آنتی\u200cویروس)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='core.device')),
            ],
        ),
    ]
