# Generated by Django 6.0 on 2025-12-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_smstemplate_systemconfig_sms_line_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='sms_line_number',
        ),
    ]
