# Generated by Django 6.0 on 2026-01-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_systemconfig_sms_line_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': 'تنظیمات سیستم', 'verbose_name_plural': 'تنظیمات سیستم'},
        ),
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sms_line_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره خط فرستنده'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='sms_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='شرکت پنل پیامکی'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='backup_interval_hours',
            field=models.IntegerField(default=24, verbose_name='بازه بکاپ (ساعت)'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='کلید API'),
        ),
    ]
