# Generated by Django 6.0 on 2026-01-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_systemconfig_options_customer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='backup_interval_hours',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='backup_frequency',
            field=models.CharField(choices=[('manual', 'دستی'), ('hourly', 'ساعتی'), ('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه')], default='daily', max_length=20, verbose_name='زمان\u200cبندی بکاپ'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='backup_retention_count',
            field=models.IntegerField(default=5, verbose_name='تعداد نگهداری فایل بکاپ'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین بکاپ موفق'),
        ),
    ]
