# Generated by Django 6.0 on 2025-12-30 07:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('price', models.BigIntegerField(verbose_name='قیمت (تومان)')),
                ('days_condition', models.IntegerField(default=30, verbose_name='مدت اعتبار (روز)')),
                ('keyword', models.CharField(blank=True, max_length=50, null=True, verbose_name='کلمه کلیدی (nod/vpn)')),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_api_key', models.CharField(blank=True, max_length=255, verbose_name='کلید API پیامک')),
                ('sms_sender', models.CharField(blank=True, max_length=50, verbose_name='شماره فرستنده')),
                ('backup_interval_hours', models.IntegerField(default=24, verbose_name='فاصله بکاپ (ساعت)')),
            ],
            options={
                'verbose_name': 'تنظیمات سیستم',
                'verbose_name_plural': 'تنظیمات سیستم',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('is_customer', models.BooleanField(default=False, verbose_name='آیا مشتری است؟')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='عملیات')),
                ('details', models.TextField(blank=True, verbose_name='جزئیات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('device', models.CharField(default='-', max_length=100, verbose_name='نوع دستگاه')),
                ('model', models.CharField(default='-', max_length=100, verbose_name='مدل')),
                ('serial', models.CharField(default='-', max_length=100, verbose_name='شماره سریال')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='تاریخ گارانتی')),
                ('buy_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ خرید')),
                ('antivirus_name', models.CharField(default='-', max_length=100, verbose_name='نام آنتی\u200cویروس')),
                ('antivirus_expiry', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا آنتی\u200cویروس')),
                ('notes', models.TextField(blank=True, default='-', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='اکانت کاربری')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='نام سرویس/محصول')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده'), ('canceled', 'لغو شده')], default='unpaid', max_length=20, verbose_name='وضعیت')),
                ('license_code', models.CharField(default='-', max_length=500, verbose_name='کد لایسنس تحویل داده شده')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='تصویر فیش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.customer', verbose_name='مشتری')),
            ],
        ),
    ]
