# Generated by Django 6.0 on 2025-12-30 12:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='شماره تماس')),
                ('device', models.CharField(blank=True, max_length=100, verbose_name='برند')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='مدل')),
                ('serial', models.CharField(blank=True, max_length=100, verbose_name='شماره سریال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات/ایرادات')),
                ('warranty_name', models.CharField(blank=True, max_length=100, verbose_name='شرکت گارانتی')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='پایان گارانتی')),
                ('buy_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پذیرش')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خروج')),
                ('has_windows', models.BooleanField(default=False, verbose_name='نصب ویندوز')),
                ('antivirus_type', models.CharField(choices=[('none', 'ندارد'), ('single', 'تک کاربره'), ('double', 'دو کاربره')], default='none', max_length=20)),
                ('antivirus_expiry', models.DateField(blank=True, null=True, verbose_name='انقضای آنتی\u200cویروس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('days_condition', models.IntegerField(default=30)),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_api_key', models.CharField(blank=True, max_length=255)),
                ('backup_interval_hours', models.IntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='شماره تماس')),
                ('is_customer', models.BooleanField(default=False, verbose_name='آیا مشتری است؟')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.customer')),
            ],
        ),
    ]
