# Generated by Django 6.0 on 2025-12-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='antivirus_type',
            field=models.CharField(choices=[('none', 'ندارد'), ('single', 'تک کاربره'), ('double', 'دو کاربره')], default='none', max_length=20, verbose_name='نوع آنتی\u200cویروس'),
        ),
    ]
